version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_CONN=postgres://username:password@db:5432/mydatabase
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
